# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c74d8486b378c1021c5d26dfc259e4fc397f1cebb873d20bc2dc7bae585e4443776b27d828d6c0c2c892d9b7a4d26ba790c2bdb9bc44851f289c1a78efa3efda

test:
  secret_key_base: 7fc1e6af74f218dc91747406029c1ca1ea2bb9998ab04bf7eeeb272b4ba316edb7de80397abb63e3a255ac2dbf04a87f46f0608803b1698eb6d806e76e28022e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
